apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'

buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://jitpack.io' }
        flatDir {
            dirs("app/libs")
        }
    }

    dependencies {
        classpath 'com.github.triplet.gradle:play-publisher:3.12.2'
    }
}

apply plugin: 'com.github.triplet.play'

android {
    def versionPropsFile = file('version.properties')  //maintains version number of apk
    Properties versionProps = new Properties()
    versionProps.load(new FileInputStream(versionPropsFile))

    def runTasks = gradle.startParameter.taskNames
    if (':app:bundleRelease' in runTasks) {  //check is release build is getting executed
        versionProps['VERSION_PATCH'] = (versionProps['VERSION_PATCH'].toInteger() + 1).toString()
        versionProps['VERSION_NUMBER'] = (versionProps['VERSION_NUMBER'].toInteger() + 1).toString()
        versionProps['VERSION_BUILD'] = (versionProps['VERSION_BUILD'].toInteger() + 1).toString()
        versionProps.store(versionPropsFile.newWriter(), null)
    }

    if (versionPropsFile.canRead()) {
        def mVersionName = "v10.0.${versionProps['VERSION_PATCH']}"
        defaultConfig {
            applicationId 'com.bhandari.music'
            minSdkVersion 24
            compileSdk = 34
            targetSdkVersion 34
            versionCode versionProps['VERSION_NUMBER'].toInteger()
            versionName "${mVersionName} Build: ${versionProps['VERSION_BUILD']}"
            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
    } else {
        throw new FileNotFoundException("Could not read version.properties!")
    }

    signingConfigs {
        release {
            def keystorePropertiesFile = rootProject.file("keystore.properties")

            if (keystorePropertiesFile.exists()) {
                def keystoreProperties = new Properties()
                keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

                storeFile file(keystoreProperties['storeFile'])
                storePassword keystoreProperties['storePassword']
                keyAlias keystoreProperties['keyAlias']
                keyPassword keystoreProperties['keyPassword']
            }
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            shrinkResources true
            //noinspection ProguardAndroidTxtUsage
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            multiDexEnabled false
        }

        debug {
            applicationIdSuffix ".dev"
            multiDexEnabled true
        }
    }


    dataBinding {
        enabled = true
    }

    kapt {
        generateStubs = true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        viewBinding = true
    }
    namespace 'com.music.player.bhandari.m'
    lint {
        abortOnError false
        disable 'MissingTranslation', 'NonConstantResourceId'
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    androidTestImplementation('androidx.test.espresso:espresso-core:3.1.0', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    //noinspection GradleCompatible
    implementation 'androidx.appcompat:appcompat:1.7.1'
    //noinspection GradleCompatible
    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
    //noinspection GradleCompatible
    implementation 'com.google.android.material:material:1.13.0'
    //noinspection GradleCompatible
    implementation 'androidx.cardview:cardview:1.0.0'
    implementation 'androidx.preference:preference-ktx:1.2.1'
    testImplementation 'junit:junit:4.13.2'

    implementation 'com.airbnb.android:lottie:6.7.1'

    //small animations for lyric loading
    implementation 'io.github.maitrungduc1410:AVLoadingIndicatorView:2.3.0'

    //slide up panel for now playing view
    implementation 'com.sothree.slidinguppanel:library:3.4.0'

    //shake detection
    implementation 'com.squareup:seismic:1.0.3'

    //glide
    //noinspection NewerVersionAvailable,GradleDependency
    implementation 'com.github.bumptech.glide:glide:3.7.0'

    //blur images
    implementation 'jp.wasabeef:blurry:4.0.1'

    //scroll smoothly and fast scroll
    implementation files('libs/snappy.aar')

    implementation 'com.simplecityapps:recyclerview-fastscroll:2.0.1'

    //jsoup and okhttp
    implementation 'org.jsoup:jsoup:1.21.2'
    implementation 'com.squareup.okhttp:okhttp:2.7.5'

    //first time info bubbles
    implementation 'com.getkeepsafe.taptargetview:taptargetview:1.15.0'

    //dialogs
    //implementation 'com.afollestad.material-dialogs:core:0.9.6.0'
    implementation project(':dialogs')

    //firebase
    //firebase
    implementation 'com.google.firebase:firebase-core:21.1.1'
    implementation 'com.google.firebase:firebase-messaging:25.0.1'
    implementation 'com.google.firebase:firebase-database:22.0.1'
    implementation 'com.google.firebase:firebase-config:23.0.1'


    //gson
    implementation 'com.google.code.gson:gson:2.13.2'

    //leak detection
    //debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.7'

    //crop images
    implementation 'com.vanniktech:android-image-cropper:4.7.0'

    //view binding
    //noinspection AnnotationProcessorOnCompilePath
    implementation 'com.jakewharton:butterknife:10.2.3'
    kapt 'com.jakewharton:butterknife-compiler:10.2.3'

    implementation 'io.github.inflationx:calligraphy3:3.1.1'
    //noinspection NewerVersionAvailable
    implementation 'io.github.inflationx:viewpump:2.0.3'

    //flow layout
    //implementation 'com.google.android:flexbox:1.0.0'
    implementation 'com.google.android.flexbox:flexbox:3.0.0'

    //kotlin
    //noinspection GradleDependency,DifferentStdlibGradleVersion
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"

    //retrofit
    implementation 'com.squareup.retrofit2:retrofit:3.0.0'
    implementation 'com.squareup.retrofit2:converter-gson:3.0.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:5.3.2'
}

repositories {
    maven {
        url 'https://maven.google.com'
    }
    mavenCentral()
}
apply plugin: 'com.google.gms.google-services'
